version: '3.4'

services:
  jenkins:
    build: .
    user: root
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_data/:/var/jenkins_home
    ports:
      - 8080:8080
      - 8081:8081
      

